name: build

on:
  push:
    branches:
    - development
    - test-cross-platform
  pull_request:
    branches:
    - development
  workflow_dispatch:

jobs:  
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        os: [windows-latest]
        framework: ["net462", "net6.0-windows", "net8.0-windows"]
    steps:
    - uses: actions/checkout@v4
    - name: Test FO-DICOM.Tests
      run: dotnet test ./Tests/FO-DICOM.Tests/FO-DICOM.Tests.csproj --configuration Release --framework ${{ matrix.framework }} --blame --runtime win-x64 --logger:"trx;LogFileName=.\results${{ matrix.framework }}.xml" --results-directory TestResults\Universal
    - name: Test FO-DICOM.Tests.Windows
      run: dotnet test ./Tests/FO-DICOM.Tests.Windows/FO-DICOM.Tests.Windows.csproj --configuration Release --framework ${{ matrix.framework }} --blame --runtime win-x64 --logger:"trx;LogFileName=.\resultsnet${{ matrix.framework }}.xml" --results-directory TestResults\Windows
    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage
    - name: Merge coverage results
      run: dotnet-coverage merge TestResults/**/coverage.cobertura.xml -f cobertura -o TestResults/coverage/coverage.xml
    - name: Debugging...
      run: tree
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
          name: test-v5-${{ matrix.framework }}.xml
          path: ./TestResults/coverage/coverage.xml
    - name: Upload code coverage 
      if: ${{ matrix.framework == 'net8.0-windows' }}
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  
  benchmarks:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Build FO-DICOM..Benchmark
      run: dotnet build ./Tests/FO-DICOM.Benchmark/FO-DICOM.Benchmark.csproj --configuration Release --framework net8.0
    - name: run benchmarks
      run: ./Tests/FO-DICOM.Benchmark/bin/Release/net8.0/fo-dicom.Benchmark.exe
    - name: Upload benchmark log
      uses: actions/upload-artifact@v4
      with:
        name: benchmark
        path: |
          ./BenchmarkDotNet.Artifacts/
          ./BenchmarkDotNet.Artifacts/results/
 

